export const env = {
  SHOPIFY_TOKEN: process.env.SHOPIFY_API_KEY,
  HOST_NAME: process.env.SHOPIFY_HOST_NAME,
  CACHE_TOKEN: process.env.CACHE_TOKEN,
  SHOPIFY_GRAPHQL_ENDPOINT: process.env.SHOPIFY_GRAPHQL_ENDPOINT,
  SHOPIFY_STOREFRONT_TOKEN: process.env.SHOPIFY_STOREFRONT_TOKEN,
};
